#!/bin/bash
if ! [ $(id -u) = 0 ]; then
	echo "This script must be run as root"
	exit 1
fi
if [[ $# -eq 0 ]] ; then
	echo 'No arguments'
	exit 1
fi
if id "$1"&>/dev/null; then
	echo ""$1" does exist"
else
	echo ""$1" doesnt exit"
	exit 1
fi
passwd -l "$1" &>/dev/null
killall -u "$1" &>/dev/null
userdel -r "$1" &>/dev/null
echo ""$1" has been obliterated"
